name: payroll-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.0
  - pandas=1.3.0
  - openpyxl=3.0.9
  - pip
  - pip:
    - fastapi==0.95.0
    - uvicorn==0.22.0
    - python-dotenv==0.19.0
    - python-multipart==0.0.5
