services:
  # Backend API service
  - type: web
    name: payroll-pro-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16

  # Frontend web service
  - type: web
    name: payroll-pro-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
