services:
  # Backend API service
  - type: web
    name: payroll-pro-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    
  # Frontend web service
  - type: web
    name: payroll-pro-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: payroll-pro-api
          type: web
          property: url
